# Generated by Django 3.2.5 on 2021-07-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_subscription_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
