# Generated by Django 3.2.5 on 2021-07-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20210713_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[], default=None, max_length=200),
        ),
    ]
