# Generated by Django 3.2.5 on 2021-07-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_subscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Half a Week', 'Half a Week'), ('Monthly', 'Monthly')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.subscription'),
        ),
    ]
