# Generated by Django 3.2.5 on 2021-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_auto_20210713_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(default='some description', max_length=500),
            preserve_default=False,
        ),
    ]
